from prometheus_client import Counter, Histogram, generate_latest, CONTENT_TYPE_LATEST

http_requests_total = Counter(
    "http_requests_total",
    "Total HTTP requests received",
)

transaction_total = Counter(
    "transaction_total",
    "Total transaction transfer requests",
)

transaction_failed_total = Counter(
    "transaction_failed_total",
    "Total failed transactions",
)

login_failed_total = Counter(
    "login_failed_total",
    "Total failed login attempts",
)

# ── 기존 이상징후 카운터 (Grafana 하위 호환) ──────────────────────────────────

anomaly_event_total = Counter(
    "anomaly_event_total",
    "Total anomaly detection events",
)

anomaly_transaction_failure_total = Counter(
    "anomaly_transaction_failure_total",
    "Anomaly: transaction failure rate exceeded",
)

anomaly_latency_total = Counter(
    "anomaly_latency_total",
    "Anomaly: API latency exceeded threshold",
)

anomaly_login_failure_total = Counter(
    "anomaly_login_failure_total",
    "Anomaly: repeated login failures",
)

anomaly_high_value_total = Counter(
    "anomaly_high_value_total",
    "Anomaly: high-value transaction detected",
)

http_request_duration_seconds = Histogram(
    "http_request_duration_seconds",
    "HTTP request duration in seconds",
)

# ── FDS 고도화 메트릭 ─────────────────────────────────────────────────────────

fds_alert_total = Counter(
    "fds_alert_total",
    "Total FDS alerts by rule type",
    ["alert_type"],
)

risk_score_histogram = Histogram(
    "transaction_risk_score",
    "Distribution of transaction risk scores (0–100)",
    buckets=[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
)

compliance_report_total = Counter(
    "compliance_report_total",
    "Total compliance reports generated by type",
    ["report_type"],
)
